---
- name: Install Apache httpd
  yum:
    name: httpd
    state: installed

- name: Enable Apache httpd
  systemd:
    name: httpd
    enabled: yes

- name: Feed html files
  copy:
    src: example.html
    dest: /var/www/html/
    owner: root
    group: root
  notify:
    - Restart httpd
